services:
  sflow-rt:
    build: ./sflow-rt
    container_name: sflow-rt
    restart: unless-stopped
    ports:
      - '6343:6343/udp'
      - '8008:8008'
      
  onos:
    image: onosproject/onos:2.5.1
    container_name: onos
    restart: unless-stopped    
    ports:
      - "6653:6653"    # OpenFlow port
      - "6640:6640"    # OpenFlow port
      - "8101:8101"    # 
      - "8181:8181"    # ONOS GUI

  influxdb:
    image: influxdb:2.7.11
    container_name: influxdb2
    restart: unless-stopped
    volumes:
      - ./influxdb2/data:/var/lib/influxdb2:rw
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USER}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=dtn
      - DOCKER_INFLUXDB_INIT_BUCKET=dtn
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN}
