services:
  onos:
    image: onosproject/onos:2.5.1
    ports:
      - "6653:6653"    # OpenFlow port
      - "6640:6640"    # OpenFlow port
      - "8101:8101"    # 
      - "8181:8181"    # ONOS GUI